### GET 요청 : 목록 조회
GET http://localhost:3000/api/snapshots
Accept: application/json

### GET 요청 : 상세 조회
GET http://localhost:3000/api/snapshots/1
Accept: application/json


### POST 요청 : 생성
POST http://localhost:3000/api/snapshots
Content-Type: application/json

{
  "name": "2025-02-17"
}

### DELETE 요청 : 삭제
DELETE http://localhost:3000/api/snapshots/1
Accept: application/json